

target-version = "py311"
line-length = 100

[lint]
# E/W - PEP8, F - поиск багов, I - сортировка импортов
select = ["E", "W", "F", "I"]
ignore = ["E203"]

[lint.isort]
# Указываем ваши локальные модули, чтобы они импортировались в самом конце
known-first-party = ["detector", "ocr_engine"]
